### ISSUE TITLE
SSL Certificate Failure

### ISSUE THREAD

**Issue by cbrum11** [googlemaps/google-maps-services-python#191] opened 2017-08-30 03:11 UTC
Newbie here... go easy on me.

Copy and pasting your example code and adding my own API key gives me the following error:

> HTTPSConnectionPool(host='maps.googleapis.com', port=443): Max retries exceeded with url: /maps/api/geocode/json?address=1600+Amphitheatre+Parkway%2C+Mountain+View%2C+CA&key=MY HIDDEN APIKEY (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

Advice?

**Comment by stephenmcd** [comment] 2017-08-30 05:50
This is a duplicate of #111

**Closed by stephenmcd** 2017-08-30 05:50 UTC

**Comment by cbrum11** [comment] 2017-08-31 05:11
In case someone else runs into this issue, I did not find my answer in #111 .  I did, however, find a solution.

Rolling back the certifi module solved the problem...

`pip uninstall -y certifi && pip install certifi==2015.04.28`

**Comment by stephenmcd** [comment] 2017-08-31 05:21
Thanks for that solution!

**Comment by cbrum11** [comment] 2017-08-31 15:38
Actually, for a much better solution to this problem (and the ability to use the most up to date certifi module) do the following:

`pip install pyOpenSSL`

`pip install requests[security]`

To check that everything is the latest and greatest...

`pip list`

**Comment by llinfeng** [comment] 2019-07-01 11:39
I reproduced the same error a bit differently. Posting here for future reference:

I stood home in China for a couple of weeks, during which all Google services are cut off, including all the Google Cloud APIs. Long story short, I set up a Shadowsocks server on a VPS and found the following code snippet super helpful on a Windows 10 machine running a Shadowsocks client on Port 7070
```
# Setups
import socket
from httplib2 import socks

#Socks5 proxy
socket.socket = socks.socksocket
socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 7070)
```
Usage: put these things before initializing the `googlemaps.client.Client` object. (These code are not mine, and I forget how I ran into it. Please advise if you know the source.)

After returning back to my office, I made a mistake of running the same Jupyter codebook on a Linux machine: so far, it does not even have `socket` installed. Thus came the exact same error message. Commenting out the code snippet above and **restarting the kernel** for the Jupyter notebook helped solve the problem.

**Comment by EraProphet** [comment] 2019-11-11 02:42
> I reproduced the same error a bit differently. Posting here for future reference:
> 
> I stood home in China for a couple of weeks, during which all Google services are cut off, including all the Google Cloud APIs. Long story short, I set up a Shadowsocks server on a VPS and found the following code snippet super helpful on a Windows 10 machine running a Shadowsocks client on Port 7070
> 
> ```
> # Setups
> import socket
> from httplib2 import socks
> 
> #Socks5 proxy
> socket.socket = socks.socksocket
> socks.setdefaultproxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 7070)
> ```
> 
> Usage: put these things before initializing the `googlemaps.client.Client` object. (These code are not mine, and I forget how I ran into it. Please advise if you know the source.)
> 
> After returning back to my office, I made a mistake of running the same Jupyter codebook on a Linux machine: so far, it does not even have `socket` installed. Thus came the exact same error message. Commenting out the code snippet above and **restarting the kernel** for the Jupyter notebook helped solve the problem.

very very very thank you ,this solution successed in my probelm

**Comment by EraProphet** [comment] 2019-11-11 02:43
@llinfeng  very very very thank you , this solution succeeded in my problem
